name: goreleaser

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # Adjust this to your project's Go version
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # Specify the version if needed, or use 'latest' for the most recent version
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}